### ISSUE TITLE
同步执行中的while循环不能超时退出

### ISSUE THREAD

**Issue by zjl410091917** [Houfeng/safeify#12]
RT，代码如下
const { Safeify } = require ("safeify");

(async ()=>{

    // 创建 safeify 实例
    const safeVm = new Safeify({
        timeout: 3000,
        asyncTimeout: 60000
    });

    // 定义 context
    const context = {
        a: 1,
        b: 2,
        system: {
            add(a, b) {
                while (1){

                }
                return (a + b) * 2;
            }
        }
    };

    // 执行动态代码
    const result= await safeVm.run(`return system.add(1,2)`, context);
    console.log('result', result);

    // 释放资源
    safeVm.destroy();

})();

**Comment by Houfeng** [comment]
`system.add` 方法是你写的呀，又不是非受信代码，你写的是受信的不会做处理。
