### ISSUE TITLE
如何处理sanbox才可以有共用方法

### ISSUE THREAD

**Issue by WebGuHui** [Houfeng/safeify#13]
![image](https://user-images.githubusercontent.com/11729740/64704545-0bab0c00-d4e1-11e9-8841-381e10410d2b.png)

给上下文提供了几个模块，是基于原型链继承的，each时把sanbox里new 实例的原型链上的东西都给抛弃了

**Comment by Houfeng** [comment]
或可尝试 unsafe 选项，如下
```js

const safeify = new Safeify({
  unsafe: {
      modules: {
         your_mod_name: your_mod_puth
     }
  }
})

```

然后，就可在 sandbox 中通过 require('your_mode_name') 加载模块了。

**Comment by WebGuHui** [comment]
![image](https://user-images.githubusercontent.com/11729740/64749463-53b14980-d548-11e9-80cc-d1b630591638.png)
如果是类似这种，我想覆盖掉默认的console，现在是基于原型链的，是不是只能改成mixin的方式来构造实例了

**Comment by Houfeng** [comment]
有两个三个方法：
1）你提个 PR 或抽个空把原型链处理一下
2）你上边提到的方法
3）用我上边提到的 requrie 的方式，但还有个 preset 可 `safeifyVM.preset('const console = requrie("console")')` ，这样后续 Sandbox 代码，可直接 console.xxx 这样写了。

**Comment by Houfeng** [comment]
我上边说的 unsafe 选项，就是用来配置允许 sandbox 中 requrie 的模块的（文件就是一个模块嘛）
