### ISSUE TITLE
【bug】worker销毁时移除了disconnect事件

### ISSUE THREAD

**Issue by WebGuHui** [Houfeng/safeify#14]
![image](https://user-images.githubusercontent.com/11729740/65027852-a4240f00-d96d-11e9-9b61-3a154497f44e.png)

![image](https://user-images.githubusercontent.com/11729740/65027834-9c646a80-d96d-11e9-80e9-4ec84217bd35.png)

注册了一个断开连接事件会触发onWorkerDisconnect函数，重新加载新worker

![image](https://user-images.githubusercontent.com/11729740/65027796-8fe01200-d96d-11e9-9a27-935a1293dafd.png)

不过这里处理worker时把事件给清楚掉了，导致不会有新worker，最后会变成无worker可用

**Comment by Houfeng** [comment]
抽个空我仔细看看

**Comment by Houfeng** [comment]
已在 safeify@5.0.4 中修复
