### ISSUE TITLE
permission denied, mkdir '/sys/fs/cgroup/cpu/safeify'

### ISSUE THREAD

**Issue by ACERY1** [Houfeng/safeify#31]
实例化 Safeify 的时候，创建文件的用户权限不够高，可以提供参数进行路径指定么，目前看代码里面是使用的默认参数

see at: https://github.com/Houfeng/safeify/blob/master/src/CGroups.ts#L25

**Comment by Houfeng** [comment]
这个不是普通文件，不能指定路径

**Comment by Houfeng** [comment]
unrestricted 选项，可关闭资源配额限制
