### ISSUE TITLE
在docker容器下报错

### ISSUE THREAD

**Issue by garming** [Houfeng/safeify#41]
报错信息：Error: EROFS: read-only file system, mkdir '/sys/fs/cgroup/cpu/safeify'

**Comment by shopee-jin** [comment]
duplicate #40 
因为cgroup需要root, 你disable cgroup即可, 直接让docker限资源

**Comment by garming** [comment]
> duplicate #40
> 因为cgroup需要root, 你disable cgroup即可, 直接让docker限资源

大佬，能简单说说怎么配置吗？？

**Comment by shopee-jin** [comment]
> > duplicate #40
> > 因为cgroup需要root, 你disable cgroup即可, 直接让docker限资源
> 
> 大佬，能简单说说怎么配置吗？？

unrestricted: true

**Comment by h330894169** [comment]
> > > duplicate #40
> > > 因为cgroup需要root, 你disable cgroup即可, 直接让docker限资源
> > 
> > 
> > 大佬，能简单说说怎么配置吗？？
> 
> unrestricted: true

这个配置是加在哪里啊？是启动docker的时候吗？

**Comment by shopee-jin** [comment]
omg, 


  const safeVm = new Safeify({
// ----> here
    unrestricted: true,
    timeout: 3000,
    asyncTimeout: 60000
  });
