### ISSUE TITLE
get {} return when put the function calling result into an object

### ISSUE THREAD

**Issue by tanlukang** [Houfeng/safeify#9]
Demo code：
```
const Safeify = require('safeify').Safeify;

(async () => {

  const safeVm = new Safeify({
    timeout: 3000,
    asyncTimeout: 60000
  });

  const context = {
    a: 1,
    b: 2,
    system: {
      add: function (a, b) {
        return (a + b) * 2;
      }
    }
  };

  const result = await safeVm.run(`
    let result = {};
    result.value = system.add(1,2);
    return result;
  `, context);
  
  console.log(result);

  safeVm.distory();

})();
```

Result:
![image](https://user-images.githubusercontent.com/7939731/53469935-cf5f1380-3a9a-11e9-82c3-a90635734c6f.png)

But if I add an await for the function calling:
`result.value = await system.add(1,2);`
it will work good ...

Do you have any ideas?  Thanks.

**Comment by Houfeng** [comment]
'await' is missing.

```js
...
result.value = await system.add(1,2);
...
```

**Comment by tanlukang** [comment]
> 'await' is missing.
> 
> ```js
> ...
> result.value = await system.add(1,2);
> ...
> ```

But system.add is a sync function. It should work if not using the 'await' before the function call

`result.value = system.add(1,2);`

Or should I put the 'await' keyword before all the function call (no matter async or sync)?

**Comment by Houfeng** [comment]
All methods on context need `await`
